### ISSUE TITLE
ATM9

### ISSUE THREAD

**Issue by DJDorcFich** [TagnumElite/ProjectE-Integration#115] opened 2024-02-14 19:41 UTC
i Dont know why and do have any errors but adding the mod to All the mods 9 it removes all emc values from everything.

**Comment by fusionmc-evilscoop** [comment] 2024-02-15 12:10
seen this too, only happened in recent update 2.46 of atm9
was fine and dandy in 2.40 
forge upgrade from  47.2.19 to 47.2.20 in this version jump

**Comment by fusionmc-evilscoop** [comment] 2024-02-15 12:35
linked to issue 114, removing chipped and atm9 works fine with emc...

Im happy to play without chipped :D
but this bug is a dupe of 114

**Comment by TagnumElite** [comment] 2024-02-25 12:11
Issue #114 was fixed in version `v7.1.1`

**Closed as completed by TagnumElite** 2024-02-25 12:11 UTC
Labels: bug
