### ISSUE TITLE
Crash on world load after installing PEI v2.0.0 for the first time.

### ISSUE THREAD

**Issue by abrachoo** [TagnumElite/ProjectE-Integration#6] opened 2019-03-26 05:43 UTC
I installed ProjectE, PEI, and a few other mods on top of v5.12.0 of the "All The Mods" modpack.

Upon loading my world, I got the following crash: https://pastebin.com/EJ26Jsi5
The crash persists when creating a new world as well.

I am using forge 14.23.5.2815

**Comment by TagnumElite** [comment] 2019-03-26 06:07
[Embers](https://minecraft.curseforge.com/projects/embers) is not supported, while [Embers Rekindled](https://minecraft.curseforge.com/projects/embers-rekindled) is.

I'll look into trying to support both of them.

**Comment by Kirbyarm** [comment] 2019-03-29 06:33
This issue is happening for me as well. I have All The Mods 3 pack installed with only 2 additional mods, ProjectE and ProjectE Integration and I get a very similar error to the one in their pastebin. Every new world in single player, or loading of a world in single player. I'm going to try hosting a server with these files and see if it will let me join..

**Comment by Kirbyarm** [comment] 2019-03-29 06:48
So the server crashes too apparently, with the same error. Or at least very similar.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ProjectE Integration (projecteintegration)
Caused by: java.lang.NoSuchFieldError: centerIngredient
	at com.tagnumelite.projecteintegration.plugins.PluginEmbersRekindled$AlchemyMapper.setup(PluginEmbersRekindled.java:62)
	at com.tagnumelite.projecteintegration.PEIntegration.serverAboutToStart(PEIntegration.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:854)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

**Comment by TagnumElite** [comment] 2019-03-29 08:19
Should be fixed in version 2.2.0

**Closed as completed by TagnumElite** 2019-03-29 08:19 UTC
Labels: bug, fixed in dev
